spring.application.name=to-do-list
# Render will override this if you use ${PORT} in your Dockerfile
server.port=8082

# 1. Changed to MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Ensure the URL also starts with mysql
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


# 2. Keep the MySQL Dialect (matching your Docker setup)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html