spring.application.name=to-do-list
# Render will override this if you use ${PORT} in your Dockerfile
server.port=8082

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Use PostgreSQL driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Use variables that Render will provide
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Hibernate Dialect for Postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update